API_ADDRESS: ":8080"
LOG_LEVEL: "debug"
LOGGER_FORMAT: "text"

DATABASE_NAME: "test"
DATABASE_USERNAME: "postgres"
DATABASE_PASSWORD: "postgres"
DATABASE_HOST: "localhost"
DATABASE_PORT: 5432
DATABASE_LOG: true
DATABASE_MAX_IDLE_CONN: 2
DATABASE_MAX_OPEN_CONN: 20